### ISSUE TITLE
Fix Create Recommendation Test Case Bug

### ISSUE THREAD

**Issue by hi348** [nyudevops-recommendation/recommendations#76]
**As a** product owner
**I need** the test case to be modified  
**So that** it properly tests the function of my product

**Assumptions:** 
* This is not actually a problem with the create function. The case is only failing because the db is not empty before the create (which is what the test case is assuming). It probably has to do with how I connected the database. Test cases should not connect to a persistent db.

**Acceptance Criteria:**
```
When I type 'nosetests'
Then all test cases should pass
```

**Comment by cheryl1223** [comment]
the database is not empty because of this line:   https://github.com/nyudevops-recommendation/recommendations/blob/636701920a68af956faf0d74341a09d8f8262d9b/service/models.py#L117

I cannot run nosetests on my side due to connection limits(I guess), could you please delete those entries and try again?
