### ISSUE TITLE
Implement Query API

### ISSUE THREAD

**Issue by hi348** [nyudevops-recommendation/recommendations#9]
**As a** user  
**I need** to be able to query the database  
**So that** I can load specifics types of recommendations for a given product  

**Assumptions:** 
* The user should pass product id, and relation type as parameters
* GET /recommendations/productid should return all products related to productid

**Acceptance Criteria:**
```
When I call HTTP GET /recommendations?product-id=123&type=upscale&customer-id=111
I should get a list of all products listed as a relation to "productid" with relationship type "category"
```

**Comment by hi348** [comment]
Why did we change the label from service.py ro models.py? When I looked at the professor's example files, the details about each function was defined in the service.py file.

**Comment by cheryl1223** [comment]
> Why did we change the label from service.py ro models.py? When I looked at the professor's example files, the details about each function was defined in the service.py file.

You're right. But we need a models.py file first to define what are the operations we can do to the database. Then in service.py we can call those methods to complete the APIs. BTW I think the name of the python file doesn't matter so maybe we can name the labels as something more meaningful like` database object model `and `controller`
Let's discuss this in the next meeting because I think we also need to change our stories. We'll need to decide what to put in our database first.
